FROM golang:1.18-alpine

COPY . /app

WORKDIR /app

RUN apk add --no-cache git make build-base libpcap-dev

RUN GOPROXY=https://goproxy.io go mod download
RUN GOPROXY=https://goproxy.io go build ./cmd/assembler
